### ISSUE TITLE
Equipment is not placed in the center of the refill station

### ISSUE THREAD

**Issue by germainelee** [smkrexus/GGJ2024-UE5#55] opened 2024-10-19 11:10 UTC
When placing Equipment on refill station, it bounces off wall and lands offset. It should be in center of the refill station.

![image](https://github.com/user-attachments/assets/f3e05bbc-bdf3-4b5e-a0e8-f469064c8777)

**Comment by smkrexus** [comment] 2024-10-19 19:10
this is a deeper issue as objects collision will cause it to bounce if there are things close by. for instance the above may be caused by bouncing off nearby wall, currently the fix is on level setup side to just place it at some distance to avoid that from happening. Submitted the setup fix in CL a804a80 but it may still happen.

Closing for now. Reopen if this issue becomes too much of a hassle

**Closed by smkrexus** 2024-10-19 19:10 UTC
Labels: bug, wontfix
